/**
 * Spanish translations for Casamadi Dashboard
 * Central place for all UI text to ensure consistency
 */

export const ES = {
  // Navigation
  nav: {
    dashboard: "Dashboard",
    conversations: "Conversaciones",
    orders: "Pedidos",
    tasks: "Tareas",
    sandbox: "Sandbox",
    users: "Usuarios",
    admin: "Admin",
    settings: "Configuración",
  },

  // Dashboard
  dashboard: {
    title: "Dashboard",
    subtitle: "Bienvenido a Casa Mädi. Monitorea tareas y operaciones en tiempo real.",
    activeConversations: "Conversaciones Activas",
    pendingOrders: "Pedidos Pendientes",
    pendingTasks: "Tareas Pendientes",
    escalations: "Escalaciones",
    recentOrders: "Pedidos Recientes",
    ordersWaiting: "Pedidos esperando ser preparados",
    recentTasks: "Tareas Recientes",
    housekeeping: "Tareas de limpieza y mantenimiento",
    readyToPrepare: "Listo para preparar",
    hotelService: "Servicio de habitación",
    viewAll: "Ver todo",
    logout: "Cerrar sesión",
    loading: "Cargando...",
    pending: "Pendiente",
  },

  // Auth
  auth: {
    email: "Correo electrónico",
    password: "Contraseña",
    signIn: "Iniciar sesión",
    signing: "Iniciando sesión...",
    staffLogin: "Inicio de sesión del personal",
    invalidCredentials: "Correo o contraseña inválidos. Intenta de nuevo.",
    accountNotFound: "No se encontró una cuenta con este correo electrónico.",
    pleaseEnter: "Por favor ingresa correo electrónico y contraseña",
    viewPassword: "Ver contraseña",
  },

  // Common
  common: {
    room: "Habitación",
    items: "artículos",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    back: "Atrás",
    cancel: "Cancelar",
    save: "Guardar",
    delete: "Eliminar",
    edit: "Editar",
    create: "Crear",
    close: "Cerrar",
    since: "desde hace",
    search: "Buscar",
    noResults: "No se encontraron resultados",
    active: "Activa",
    resolved: "Resuelta",
    inactive: "Inactiva",
    openMenu: "Abrir menú",
    actions: "Acciones",
    previous: "Anterior",
    next: "Siguiente",
    saving: "Guardando...",
    refresh: "Actualizar",
  },

  // Conversations
  conversations: {
    title: "Conversaciones",
    searchPlaceholder: "Buscar por nombre, teléfono o habitación...",
    empty: "No hay conversaciones",
    notFound: "No se encontraron conversaciones",
    channel: "Canal",
    guest: "Huésped",
    lastMessage: "Último mensaje",
    status: "Estado",
    unread: "No leído",
    active: "Activa",
    of: "de",
    // Thread view
    threadTitle: "Conversación con",
    guestInfo: "Información del Huésped",
    phone: "Teléfono",
    email: "Correo",
    roomNumber: "Número de Habitación",
    typePlaceholder: "Escribir mensaje...",
    send: "Enviar",
    sendingMessage: "Enviando...",
    messageError: "Error al enviar mensaje",
    noMessages: "No hay mensajes aún",
    loadingMessages: "Cargando mensajes...",
    backToList: "Volver a conversaciones",
  },

  // Orders
  orders: {
    title: "Pedidos",
    pending: "Pendiente",
    preparing: "Preparando",
    ready: "Listo",
    delivered: "Entregado",
    room: "Habitación",
    items: "artículos",
    guest: "Huésped",
    status: "Estado",
    created: "Creado",
    orderDetails: "Detalles del Pedido",
    emptyState: "No hay pedidos",
    dragTip: "Arrastra para cambiar estado",
  },

  // Public Menu
  menu: {
    title: "Menú",
    subtitle: "Ordena desde tu habitación",
    notAvailable: "Menú no disponible",
    noItems: "No hay elementos disponibles en el menú",
    itemCount: "elementos",
    sectionBreakfast: "Desayuno",
    sectionLunchDinner: "Comida y cena",
    sectionAnytime: "Disponible 24/7",
    helpTitle: "¿Necesitas ayuda?",
    helpDescription: "Contáctanos por chat o llama a recepción para hacer tu pedido.",
    openChat: "Abrir chat",
  },

  // Settings
  settings: {
    notifications: "Notificaciones",
    navigation: "Navegación",
    home: "Inicio",
    appearance: "Apariencia",
    messagesMedia: "Mensajes y multimedia",
    languageRegion: "Idioma y región",
    accessibility: "Accesibilidad",
    markAsRead: "Marcar como leído",
    audioVideo: "Audio y vídeo",
    connectedAccounts: "Cuentas conectadas",
    privacyVisibility: "Privacidad y visibilidad",
    advanced: "Avanzado",
  },

  // Sandbox
  sandbox: {
    title: "Sandbox - Testing Agent",
    newTest: "Nuevo Test",
    simulatePayment: "Simular Pago",
    debug: "Debug",
    sessionId: "ID de Sesión",
    messages: "Mensajes",
    channel: "Canal",
    status: "Estado",
    ready: "Listo",
    quickCommands: "Comandos Rápidos",
  },

  // Users Admin
  users: {
    title: "Gestión de Usuarios",
    description: "Administra el personal y permisos del hotel",
    addUser: "Agregar Usuario",
    editUser: "Editar Usuario",
    addUserDesc: "Crea un nuevo usuario con rol y credenciales",
    editUserDesc: "Actualiza la información del usuario",
    name: "Nombre",
    firstName: "Nombre",
    lastName: "Apellido",
    phone: "Teléfono",
    position: "Posición",
    role: "Rol",
    tasks: "Tareas Disponibles",
    taskDescription: "Selecciona las tareas que este usuario puede realizar",
    roleAdmin: "Administrador",
    roleManager: "Gerente",
    roleFrontDesk: "Recepción",
    roleRoomService: "Servicio de Habitación",
    roleHousekeeping: "Limpieza",
    createdAt: "Creado",
    searchPlaceholder: "Buscar por correo...",
    columns: "Columnas",
    noUsers: "No hay usuarios registrados",
    noUsersDesc: "Comienza creando el primer usuario del hotel",
    usersTotal: "usuario(s) total",
    fillAllFields: "Por favor completa todos los campos",
    passwordRequired: "La contraseña es requerida para nuevos usuarios",
    userCreatedSuccess: "Usuario creado exitosamente",
    userUpdatedSuccess: "Usuario actualizado exitosamente",
    userDeletedSuccess: "Usuario eliminado exitosamente",
    errorSavingUser: "Error al guardar el usuario",
    errorDeletingUser: "Error al eliminar el usuario",
    errorFetchingUsers: "Error al cargar los usuarios",
    deleteConfirmTitle: "¿Eliminar usuario?",
    deleteConfirmDesc: "¿Estás seguro de que deseas eliminar a",
    saving: "Guardando...",
    // Available tasks
    taskCheckAvailability: "Verificar Disponibilidad",
    taskManageReservations: "Gestionar Reservas",
    taskProcessPayments: "Procesar Pagos",
    taskManageOrders: "Gestionar Pedidos",
    taskHandleEscalations: "Gestionar Escalaciones",
    taskAnswerInquiries: "Responder Consultas",
    taskCheckIn: "Check-in",
    taskCheckOut: "Check-out",
    taskManageHousekeeping: "Gestionar Limpieza",
  },

  settingsDesc: "Personaliza tu configuración aquí",
}

